.contract_migration_variables:
    variables:
        APP_NAME: contract-migration
        DOCKERFILE_PATH: docker/Dockerfile_ci
        CONTEXT: apps/$APP_NAME

build-mr-contract-migration:
    extends:
        - .py_build_merge_request
        - .contract_migration_variables
    rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
          - apps/contract-migration/**/*
      when: always

build-push-contract-migration:
    extends:
        - .py_build_push
        - .contract_migration_variables
    rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
          - apps/contract-migration/**/*
      when: always
